# Generated by Django 3.1.3 on 2020-11-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Aéroport')),
                ('ville', models.CharField(max_length=50, verbose_name='ville')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Avion')),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Equipage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Prénom ')),
                ('prenom', models.CharField(max_length=50, verbose_name='Nom ')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse ')),
                ('salaire', models.FloatField(verbose_name='salaire')),
                ('numero_securite_sociale', models.CharField(max_length=50, unique=True, verbose_name='N sécurité sociale')),
                ('fonction', models.CharField(max_length=50, verbose_name='fonction')),
            ],
            options={
                'unique_together': {('prenom', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Liaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='prix')),
                ('aeroport_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_airporl_to_airport', to='wwwApp.aeroport')),
                ('aeroport_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_airport_to_airport', to='wwwApp.aeroport')),
            ],
            options={
                'unique_together': {('aeroport_depart', 'aeroport_destination')},
            },
        ),
        migrations.CreateModel(
            name='Pilote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom ')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom ')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse ')),
                ('salaire', models.FloatField(verbose_name='salaire')),
                ('numero_securite_sociale', models.CharField(max_length=50, unique=True, verbose_name='N sécurité sociale')),
                ('nombre_heure', models.IntegerField()),
                ('numero_licence', models.CharField(max_length=50, unique=True, verbose_name='N licence')),
            ],
            options={
                'unique_together': {('prenom', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField(verbose_name='Temps de départ')),
                ('date_arrivee', models.DateField(verbose_name="Temps d'arrivée")),
                ('places_disponibles', models.IntegerField(verbose_name='places disponibles')),
                ('places_totales', models.IntegerField(verbose_name='places totales')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wwwApp.avion', verbose_name='Avion')),
                ('equipage1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equi1_to_equipage', to='wwwApp.equipage', verbose_name='equipage1')),
                ('equipage2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equi2_to_equipage', to='wwwApp.equipage', verbose_name='equipage2')),
                ('liaison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liaison1_to_liaiosn', to='wwwApp.liaison', verbose_name='liaison')),
                ('pilote1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew1_to_crew', to='wwwApp.pilote', verbose_name='Pilote1')),
                ('pilote2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew2_to_crew', to='wwwApp.pilote', verbose_name='Pilote2')),
            ],
            options={
                'unique_together': {('date_depart', 'date_arrivee', 'liaison')},
            },
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billet_to_client', to='wwwApp.client')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billet_to_flight', to='wwwApp.vol')),
            ],
        ),
    ]
