# Generated by Django 3.1.3 on 2020-11-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwApp', '0002_auto_20201127_2253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billet',
            unique_together={('flight', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='vol',
            unique_together={('date_depart', 'date_arrivee', 'heure_depart', 'heure_arrivee', 'liaison')},
        ),
    ]
