# Generated by Django 3.1.3 on 2020-11-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwApp', '0003_auto_20201128_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('prenom', 'nom')},
        ),
    ]
